name: 'CMake'
inputs:
  # The default clone path of actions/checkout equals $GITHUB_WORKSPACE (or ${{ github.workspace }}).
  cmake-source-dir:
    description: 'Path to the top level of the source tree (aka root cmake directory).'
    required: true
    default: ${{ github.workspace }}
  cmake-build-dir:
    description: 'Path to directory where the source will be build.'
    required: true
    default: ${{ github.workspace }}/build
  cmake-install-prefix:
    description: 'Path to directory where the build will be installed.'
    required: true
    default: ${{ github.workspace }}/install
  cmake-build-type:
    description: 'CMake build type. E.g.: Release.'
    required: false
    default: 'Release'
  cmake-configure-flags:
    description: 'CMake configure flags that can be set as -D<key>=<value>'
    required: false
    default: ''
  cmake-install:
    description: 'Installs the build when set to true.'
    required: false
    default: false
  cmake-ctest:
    description: 'Tests the build using CTest when set to true.'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Configure
      shell: bash
      # Visual Studio ignores -DCMAKE_BUILD_TYPE=$BUILD_TYPE and will use cmake --config $BUILD_TYPE
      # Make like generators will do the opposite.
      run: cmake -S $(echo "${{ inputs.cmake-source-dir }}" | awk '{gsub(/\\/,"/", $0); print}') -B $(echo "${{ inputs.cmake-build-dir }}" | awk '{gsub(/\\/,"/", $0); print}') -DCMAKE_BUILD_TYPE=${{ inputs.cmake-build-type }} ${{ inputs.cmake-configure-flags }}
    
    - name: Build
      shell: bash
      run: cmake --build $(echo "${{ inputs.cmake-build-dir }}" | awk '{gsub(/\\/,"/", $0); print}') --config ${{ inputs.cmake-build-type }} -j 3
    
    - name: Install
      shell: bash
      # macos-latest doesn't support ${var,,} for tolower
      # Composite actions don't seem to support an if: ${{ <expression> }}, hence the bash based if.
      run: |
        if [[ $(echo "${{ inputs.cmake-install }}" | awk '{print tolower($0)}') = "true" ]]; then 
          cmake --install $(echo "${{ inputs.cmake-build-dir }}" | awk '{gsub(/\\/,"/", $0); print}') --prefix $(echo "${{ inputs.cmake-install-prefix }}" | awk '{gsub(/\\/,"/", $0); print}') --config ${{ inputs.cmake-build-type }}
        else
          echo "Install skipped."
        fi

    - name: CTest
      shell: bash
      run: |
        if [[ $(echo "${{ inputs.cmake-ctest }}" | awk '{print tolower($0)}') = "true" ]]; then 
          ctest --test-dir $(echo "${{ inputs.cmake-build-dir }}" | awk '{gsub(/\\/,"/", $0); print}') -C ${{ inputs.cmake-build-type }} -j 3
        else
          echo "CTest skipped."
        fi
